channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=25.0
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - numpy==2.1.1
  - pandas==2.2.3
  - psutil==6.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
