name: sekwencja

on: 
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job 1 running"

  job2:
    runs-on: ubuntu-latest
    needs: job1  # job2 czeka, aż job1 się zakończy
    steps:
      - name: Step 2
        run: echo "Job 2 running"

  job3:
    runs-on: ubuntu-latest
    needs: job2  # job3 czeka, aż job2 się zakończy
    steps:
      - name: Step 3
        run: echo "Job 3 running"